#!/usr/bin/env python

import sys

import job_wrapper


def run_job(conf_file):
	wrapper = job_wrapper.JobWrapper(conf_file)
	wrapper.run()


def usage():
	print("Must give a job description file as the only argument.")


if __name__ == "__main__":
	if len(sys.argv) != 2:
		usage()
		sys.exit(-1)

	conf_file = sys.argv[1]

	run_job(conf_file)
